### ISSUE TITLE
Cura crashes

### ISSUE THREAD

**Issue by thinkingalaud** [inanutshellus/cura-plugin-pause-at-height-filament-swap#2]
Cura crashes when using this plugin with this stacktrace
```
Traceback (most recent call last):
  File "cura/CuraApplication.py", line 1118, in event
    return super().event(event)
  File "UM/Qt/QtApplication.py", line 500, in event
    event._function_event.call()
  File "UM/Event.py", line 218, in call
    self._function(*self._args, **self._kwargs)
  File "cura/Settings/MachineManager.py", line 179, in setInitialActiveMachine
    self.setActiveMachine(active_machine_id)
  File "cura/Settings/MachineManager.py", line 341, in setActiveMachine
    self._application.setGlobalContainerStack(global_stack)
  File "cura/CuraApplication.py", line 690, in setGlobalContainerStack
    super().setGlobalContainerStack(stack)
  File "UM/Application.py", line 289, in setGlobalContainerStack
    self.globalContainerStackChanged.emit()
  File "UM/Signal.py", line 216, in emit
    self.__handleEmitIndirect(*args, **kwargs)
  File "UM/Signal.py", line 323, in __handleEmitIndirect
    self.__performEmit(*args, **kwargs)
  File "UM/Signal.py", line 357, in __performEmit
    func(dest, *args, **kwargs)
  File "/Applications/Ultimaker-Cura.app/Contents/MacOS/share/cura/plugins/PostProcessingPlugin/PostProcessingPlugin.py", line 303, in _onGlobalContainerStackChanged
    self._restoreScriptInforFromMetadata()
  File "/Applications/Ultimaker-Cura.app/Contents/MacOS/share/cura/plugins/PostProcessingPlugin/PostProcessingPlugin.py", line 282, in _restoreScriptInforFromMetadata
    new_script.initialize()
  File "/Applications/Ultimaker-Cura.app/Contents/MacOS/share/cura/plugins/PostProcessingPlugin/Script.py", line 50, in initialize
    self._definition.deserialize(json.dumps(setting_data))
  File "UM/Settings/DefinitionContainer.py", line 325, in deserialize
    parsed, is_valid = self.readAndValidateSerialized(serialized)
  File "UM/Settings/DefinitionContainer.py", line 275, in readAndValidateSerialized
    self._verifyJson(parsed)
  File "UM/Settings/DefinitionContainer.py", line 447, in _verifyJson
    raise IncorrectDefinitionVersionError("Definition uses version {0} but expected version {1}".format(json_dict["version"], self.Version))
UM.Settings.DefinitionContainer.IncorrectDefinitionVersionError: Definition uses version 3 but expected version 2
```
I'm using Cura 5.1.0

Not sure why version was changed in acccaa784f2e0b50e59adacfffce363c44fb0976, but changing it back to 2 works for me

**Comment by inanutshellus** [comment]
Thanks for letting me know @thinkingalaud. I reverted the version. Give it a try! 
And... while I've got your attention, it'd be rad if you tried out the new longer song option. The dude that asked for it hasn't let me know it worked for him... so... it'd be cool to see confirmation somewhere that it's functioning on someone *else's* machine.

**Comment by ihurrahi** [comment]
Just tested it last night - seems to work for me!

**Comment by thinkingalaud** [comment]
just tested this last night - seems to work for me!
